### ISSUE TITLE
External Monitors reset to black whenever someone enters render distance

### ISSUE THREAD

**Issue by gamax92** [gamax92/OCLights2#1]
When ever someone enters render distance of the External Monitor, they all reset to black.
They keep all of their allocated textures and settings, just the main one switches to black.

**Comment by ds84182** [comment]
Huh.

**Comment by gamax92** [comment]
So, when someone enters rendering distance, everyone gets a NET_GPUTILE
NET_GPUTILE calls a function which happens to call propogateTerminal
propogateTerminal makes a new Monitor object
and Monitor object's fill themselves with black on init

Now ... how to fix ...

**Comment by ds84182** [comment]
Don't fill with black then?

**Comment by ds84182** [comment]
Or copy old content into new monitor
